<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-09-18T12:07:27Z" name="Default suite" finished-at="2019-09-18T12:08:36Z" duration-ms="69474">
    <groups>
    </groups>
    <test started-at="2019-09-18T12:07:27Z" name="Default test" finished-at="2019-09-18T12:08:36Z" duration-ms="69474">
      <class name="com.example.restapis.tests.PetTests">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.example.restapis.tests.PetTests@6236eb5f]" started-at="2019-09-18T13:07:27Z" name="beforeClass" finished-at="2019-09-18T13:07:28Z" duration-ms="1131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="getPetsByStatus()[pri:0, instance:com.example.restapis.tests.PetTests@6236eb5f]" started-at="2019-09-18T13:07:28Z" name="getPetsByStatus" finished-at="2019-09-18T13:07:33Z" duration-ms="5341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPetsByStatus -->
        <test-method signature="getPetsByStatusAndDoChecks()[pri:0, instance:com.example.restapis.tests.PetTests@6236eb5f]" started-at="2019-09-18T13:07:33Z" name="getPetsByStatusAndDoChecks" finished-at="2019-09-18T13:08:36Z" duration-ms="62949" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4185] but found [4189]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4185] but found [4189]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at com.example.restapis.tests.PetTests.getPetsByStatusAndDoChecks(PetTests.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPetsByStatusAndDoChecks -->
      </class> <!-- com.example.restapis.tests.PetTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
